name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build
      run: |
        npm install
        npm run build
      env:
        VUE_APP_APIKEY: ${{ secrets.VUE_APP_APIKEY }}
        VUE_APP_APPID: ${{ secrets.VUE_APP_APPID }}
        VUE_APP_AUTHDOMAIN: ${{ secrets.VUE_APP_AUTHDOMAIN }}
        VUE_APP_DATABASEURL: ${{ secrets.VUE_APP_DATABASEURL }}
        VUE_APP_MEASUREMENTID: ${{ secrets.VUE_APP_MEASUREMENTID }}
        VUE_APP_MESSAGINGSENDERID: ${{ secrets.VUE_APP_MESSAGINGSENDERID }}
        VUE_APP_PROJECTID: ${{ secrets.VUE_APP_PROJECTID }}
        VUE_APP_STORAGEBUCKET: ${{ secrets.VUE_APP_STORAGEBUCKET }}

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.TOKEN_KEY }}
        BRANCH: gh-pages
        FOLDER: dist

        
      
