name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build
      run: |
        npm install
        npm run build
      env:
        VUE_APP_APIKEY: ${{ secrets.VUE_APP_APIKEY }}
        APPID: ${{ secrets.VUE_APP_APPID }}
        AUTHDOMAIN: ${{ secrets.VUE_APP_AUTHDOMAIN }}
        DATABASEURL: ${{ secrets.VUE_APP_DATABASEURL }}
        MEASUREMENTID: ${{ secrets.VUE_APP_MEASUREMENTID }}
        MESSAGINGSENDERID: ${{ secrets.VUE_APP_MESSAGINGSENDERID }}
        PROJECTID: ${{ secrets.VUE_APP_PROJECTID }}
        STORAGEBUCKET: ${{ secrets.VUE_APP_STORAGEBUCKET }}
        THEO_APP_APIKEY: ${{ secrets.THEO_APP_APIKEY }}

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.TOKEN_KEY }}
        BRANCH: gh-pages
        FOLDER: dist

        
      
